-- QUITAR RLS TEMPORALMENTE PARA PROBAR
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE circles DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE places DISABLE ROW LEVEL SECURITY;
ALTER TABLE place_visits DISABLE ROW LEVEL SECURITY;
