platform :ios, '14.0'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

flutter_application_path = File.join(__dir__, '..')
eval(File.read(File.join(flutter_application_path, '.flutter', 'flutter_export_environment.sh')))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.join(File.dirname(__dir__), '.flutter')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end